<h1>Add Category</h1>
<hr>
<form action="" method="post">
<table class="table">
    <tr>
        <td style="padding: 30px;">Title</td>
        <td><?php echo $this->form->title; ?></td>
    </tr>

    <tr>
        <td style="padding: 30px;">Content</td>
        <td><?php echo $this->form->content; ?></td>
    </tr>
    <tr>
        <td style="padding: 30px;">User</td>
        <td><?php echo $this->form->user_id; ?></td>
    </tr>

    <tr>
        <td colspan="2"><?php echo $this->form->submit; ?></td>
    </tr>
     
</table>
</form>
