<h1>Materials Content</h1>
<br />

<?php
echo "<td ><a class='btn btn-primary' href='".$this->baseUrl()."/MaterialContent/add/'>Add Material</a><br/><br/>";
//	echo "<a href='".$this->baseUrl()."/users/logout/'>Logout </a> <br />";
    echo '<table class="table">';
    echo '<tr>';
	echo "<th> ID </th>";
	echo "<th> title </th>";
	echo "<th> Description </th>";
//        echo "<th> Content_path </th>";
        echo "<th> Actions </th>";
	echo '</tr>';
    foreach ($this->materials as $material){
        
        echo '<tr><td>'.$material['id'].'</td>';
        echo '<td>'.$material['title'].'</td>';
        echo '<td>'.$material['description'].'</td>';
//        echo '<td>'.$material['content_path'].'</td>';
        echo "<td ><a class='btn btn-primary' href='".$this->baseUrl()."/Materialcontent/edit/id/".$material['id']."'> Edit </a><a class='btn btn-danger' href='".$this->baseUrl()."/Materialcontent/delete/id/".$material['id']."'> Delete </a></td>";
        echo '</tr>';
        
	}

?>


