<h1>Materials Content</h1>
<br />
<a href=""></a>
<?php
//echo "<td ><a class='btn btn-primary' href='".$this->baseUrl()."/Materialcontent/add/'>Add Material</a><br/><br/>";
//	echo "<a href='".$this->baseUrl()."/users/logout/'>Logout </a> <br />";
echo '<table class="table">';
echo '<tr>';
echo "<th> Content_path </th>";
echo "<th> Actions </th>";
echo '</tr>';
foreach ($this->data as $data) {


//        echo '<tr><td>'.$material['id'].'</td>';
    echo "<tr><td><a href='" . $this->baseUrl() . "/Materialcontent/display/content/" . $data['content_path'] ."'>".$data['content_path']."</a></td>";
    echo "<td ><a class='btn btn-danger' href='" . $this->baseUrl() . "/Materialcontent/delete/id/" . $data['id'] . "'> Delete </a><a class='btn btn-primary' href='" . $this->baseUrl() . "/Materialcontent/edit/id/" . $data['id'] . "'> Edit </a><a class='btn btn-primary' href='".$this->baseUrl()."/comments/show/id/".$data['id']."'> Comment </a>";

    if ($data['is_locked'] == '1') {
        echo "<a class='btn btn-danger' href='" . $this->baseUrl() . "/Materialcontent/unlock/id/" . $data['id'] ."/mid/".$data['material_id']. "'> Unlock </a>";
    } else {
        echo "<a class='btn btn-danger' href='" . $this->baseUrl() . "/Materialcontent/lock/id/" . $data['id'] ."/mid/".$data['material_id']. "'> lock </a>";
    }
    if ($data['is_show'] == '1') {
        echo "<a class='btn btn-primary' href='" . $this->baseUrl() . "/Materialcontent/hide/id/" . $data['id'] ."/mid/".$data['material_id']. "'> Hide </a></td>";
    } else {
        echo "<a class='btn btn-primary' href='" . $this->baseUrl() . "/Materialcontent/show/id/" . $data['id'] ."/mid/".$data['material_id']. "'> show </a></td>";
    }
    echo '</tr>';
}
?>


