<h1>Add Materials</h1>
<hr>
<form action="http://localhost/ZendProject/public/materials/edit/id/<?php echo $this->id; ?>" method="post">
<table class="table">
    <tr>
        <td style="padding: 30px;">Title</td>
        <td><?php echo $this->form->title; ?></td>
    </tr>
    <tr>
        <td style="padding: 30px;">Approved</td>
        <td><?php echo $this->form->is_approved; ?></td>
    </tr>
    <tr>
        <td style="padding: 30px;">Published</td>
        <td><?php echo $this->form->is_published; ?></td>
    </tr>
    <tr>
        <td style="padding: 30px;">Shown</td>
        <td><?php echo $this->form->is_shown; ?></td>
    </tr>
    <tr>
        <td style="padding: 30px;">Material Type</td>
        <td><?php echo $this->form->material_type_id; ?></td>
    </tr>
    <tr>
        <td style="padding: 30px;">Course</td>
        <td><?php echo $this->form->course_id; ?></td>
    </tr>
    <tr>
        <td style="padding: 30px;">User</td>
        <td><?php echo $this->form->user_id; ?></td>
    </tr>
    <tr>
        <td colspan="2"><?php echo $this->form->submit; ?></td>
    </tr>
</table>
</form>
