<?php
echo $this->headLink()->appendStylesheet($this->baseUrl('css/main.css'));
?>
<div id="page-wrapper">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">

                <div class="panel-body">
                    <div class="row">
                        <div class="col-lg-12">
                            <?php
                            echo $this->form;
                            ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>