<div class="container">
    <div class="wrapper">
<?php
	//echo $this->x;
        $this->headLink()->appendStylesheet($this->baseUrl('css/main.css'));
	echo "<a href='".$this->baseUrl()."/users/logout/'>Logout </a> <br />";
	foreach ($this->users as $user){
	echo "<label> ID: </label>".$user['id'].'<br />';
        echo "<br /><img width='100' height='100' src='".$this->baseUrl()."/images/profile_images/".$user['photo']."'/>";
	echo "<label> Username: </label>".$user['username'].'<br />';
	echo "<label> Password: </label>".$user['password'].'<br />';
        echo "<label> Country: </label>".$user['country'].'<br />';
	echo "<label> Email: </label>".$user['email'].'<br />';
	echo "<label> Gender: </label>".$user['gender'].'<br />';
        echo "<label> Signature: </label>".$user['signature'].'<br />';
	echo "<a href='".$this->baseUrl()."/users/edit/id/".$user['id']."'> Edit </a> "."<a href='".$this->baseUrl()."/users/delete/id/".$user['id']."'> Delete </a> <br />";
	echo str_repeat('*', 100).'<br />';
	}

?>
    </div>
</div>