<?php echo $this->doctype(); ?>
<html>
    <head>
        
        <?php echo $this->headMeta(); ?>
        <?php echo $this->headTitle(); ?>
        <?php echo $this->headLink(); ?>
       
    </head>

<body style="background-color: white;">

    <div id="wrapper">

     <?php echo $this->layout()->content; ?>


            <!-- /.container-fluid -->
    </div>
        <!-- /#page-wrapper -->
    
</body>

</html>
