<?php echo $this->doctype(); ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>Online Courses</title>

        <!-- Mobile Specific Metas
        ================================================== -->
        <meta name="viewport" content="width=device-width, initial-scale=1">


        <!-- CSS
        ================================================== -->       

        <?php echo $this->headMeta(); ?>
        <?php echo $this->headTitle(); ?>
        <?php
        echo $this->headLink();
        echo $this->headLink()->appendStylesheet($this->baseUrl('css/style.css'));
        //  echo $this->headLink()->appendStylesheet('http://fonts.googleapis.com/css?family=Merriweather');
        //  echo $this->headLink()->appendStylesheet('http://fonts.googleapis.com/css?family=Varela');
        ?>  

    </head>
    <body>    

        <!-- SCROLL TOP BUTTON -->
        <a class="scrollToTop" href="#"></a>
        <!-- END SCROLL TOP BUTTON -->

        <!--=========== BEGIN HEADER SECTION ================-->
        <header id="header">
            <!-- BEGIN MENU -->
            <div class="menu_area">
                <nav class="navbar navbar-default navbar-fixed-top" role="navigation">  <div class="container">
                        <div class="navbar-header">
                            <!-- FOR MOBILE VIEW COLLAPSED BUTTON -->
                            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                                <span class="sr-only">Toggle navigation</span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                            </button>
                            <!-- LOGO -->
                            <!-- TEXT BASED LOGO -->
                            <a class="navbar-brand"  href="<?php echo $this->baseUrl() ?>/materials/index/" >Online <span>Courses</span></a>              
                            <!-- IMG BASED LOGO  -->
                             <!-- <a class="navbar-brand" href="index.html"><img src="img/logo.png" alt="logo"></a>  -->            

                        </div>
                        <div id="navbar" class="navbar-collapse collapse">
                            <ul id="top-menu" class="nav navbar-nav navbar-right main-nav">
                                <li class="active"><a href="<?php echo $this->baseUrl() ?>/">Home</a></li>

                                <li class="dropdown">
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Category<span class="caret"></span></a>
                                    <ul class="dropdown-menu" role="menu">
                                        <?php
                                        foreach ($this->courses as $course) {
                                            ?>
                                            <li><a href="#"><?php echo $course['title'] ?></a></li>
                                            <?php
                                        }
                                        ?>                    
                                    </ul>
                                </li>      
                                <li><a href= <?php echo $this->baseUrl() . '/requests/add/'; ?>>Request Material</a></li>

                                <li><a href= <?php echo $this->baseUrl() . '/users/view/id/' . $this->user_id; ?>>Profile</a></li>
                                <li><a href=<?php echo $this->baseUrl() . '/users/edit/id/' . $this->user_id; ?>>Edit Profile</a></li>
                                <?php
                                if ($this->is_admin == "1") {
                                    ?>  
                                    <li><a href=<?php echo $this->baseUrl() . '/users/index/'; ?>>Admin panel</a></li>
                                    <?php
                                }
                                ?>  
                                <li><a href="<?php echo $this->baseUrl() ?>/users/logout/">Logout</a></li>
                            </ul>           
                        </div><!--/.nav-collapse -->
                    </div>     
                </nav>  
            </div>
            <!-- END MENU -->    
        </header>
        <!--=========== END HEADER SECTION ================--> 

        <section id="aboutUs">
            <div class="container">
                <div class="row">
                    <?php echo $this->layout()->content; ?>

                </div>
            </div>
        </section>

        <!--=========== BEGIN WHY US SECTION ================-->
        <section id="whyUs">
            <!-- Start why us top -->
            <div class="row">        
                <div class="col-lg-12 col-sm-12">
                    <div class="whyus_top">
                        <div class="container">
                            <!-- Why us top titile -->
                            <div class="row">
                                <div class="col-lg-12 col-md-12"> 
                                    <div class="title_area">
                                        <h2 class="title_two">Why Us</h2>
                                        <span></span> 
                                    </div>
                                </div>
                            </div>
                            <!-- End Why us top titile -->
                            <!-- Start Why us top content  -->
                            <div class="row">
                                <div class="col-lg-3 col-md-3 col-sm-3">
                                    <div class="single_whyus_top wow fadeInUp">
                                        <div class="whyus_icon">
                                            <span class="fa fa-desktop"></span>
                                        </div>
                                        <h3>Technology</h3>
                                        <p>when an unknown printer took a galley of type and scrambled it to make a type specimen book</p>
                                    </div>
                                </div>
                                <div class="col-lg-3 col-md-3 col-sm-3">
                                    <div class="single_whyus_top wow fadeInUp">
                                        <div class="whyus_icon">
                                            <span class="fa fa-users"></span>
                                        </div>
                                        <h3>Best Tutor</h3>
                                        <p>when an unknown printer took a galley of type and scrambled it to make a type specimen book</p>
                                    </div>
                                </div>
                                <div class="col-lg-3 col-md-3 col-sm-3">
                                    <div class="single_whyus_top wow fadeInUp">
                                        <div class="whyus_icon">
                                            <span class="fa fa-flask"></span>
                                        </div>
                                        <h3>Practical Training</h3>
                                        <p>when an unknown printer took a galley of type and scrambled it to make a type specimen book</p>
                                    </div>
                                </div>
                                <div class="col-lg-3 col-md-3 col-sm-3">
                                    <div class="single_whyus_top wow fadeInUp">
                                        <div class="whyus_icon">
                                            <span class="fa fa-support"></span>
                                        </div>
                                        <h3>Support</h3>
                                        <p>when an unknown printer took a galley of type and scrambled it to make a type specimen book</p>
                                    </div>
                                </div>
                            </div>
                            <!-- End Why us top content  -->
                        </div>
                    </div>
                </div>        
            </div>
            <!-- End why us top -->
        </section>
        <!--=========== END WHY US SECTION ================-->


        <!--=========== BEGIN STUDENTS TESTIMONIAL SECTION ================-->
        <section id="studentsTestimonial">
            <div class="container">
                <!-- Our courses titile -->
                <div class="row">
                    <div class="col-lg-12 col-md-12"> 
                        <div class="title_area">
                            <h2 class="title_two">What our Student says</h2>
                            <span></span> 
                        </div>
                    </div>
                </div>
                <!-- End Our courses titile -->

                <!-- Start Our courses content -->
                <div class="row">
                    <div class="col-lg-12 col-md-12 col-sm-12">
                        <div class="studentsTestimonial_content">              
                            <div class="row">
                                <!-- start single student testimonial -->
                                <div class="col-lg-4 col-md-4 col-sm-4">
                                    <div class="single_stsTestimonial wow fadeInUp">
                                        <div class="stsTestimonial_msgbox">
                                            <p>when an unknown printer took a galley of type and scrambled it to make a type specimen book</p>
                                        </div>
                                        <?php echo "<img alt='img' class='stsTesti_img'  src='" . $this->baseUrl() . "/images/temp_img/author1.jpg'/>"; ?>
                                        <div class="stsTestimonial_content">
                                            <h3>Yasmin Mohamed</h3>                      
                                            <span>Ex. Student</span>
                                            <p>Software Department</p>
                                        </div>
                                    </div>
                                </div>
                                <!-- End single student testimonial -->
                                <!-- start single student testimonial -->
                                <div class="col-lg-4 col-md-4 col-sm-4">
                                    <div class="single_stsTestimonial wow fadeInUp">
                                        <div class="stsTestimonial_msgbox">
                                            <p>when an unknown printer took a galley of type and scrambled it to make a type specimen book.scrambled it to make a type specimen book</p>
                                        </div>
                                        <?php echo "<img alt='img' class='stsTesti_img'  src='" . $this->baseUrl() . "/images/temp_img/author2.jpg'/>"; ?>
                                        <div class="stsTestimonial_content">
                                            <h3>Sherif Elkhaiat</h3>                      
                                            <span>Ex. Student</span>
                                            <p>Software Department</p>
                                        </div>
                                    </div>
                                </div>
                                <!-- End single student testimonial -->
                                <!-- start single student testimonial -->
                                <div class="col-lg-4 col-md-4 col-sm-4">
                                    <div class="single_stsTestimonial wow fadeInUp">
                                        <div class="stsTestimonial_msgbox">
                                            <p>when an unknown printer took a galley of type and scrambled it to make a type specimen book</p>
                                        </div>
                                        <?php echo "<img alt='img' class='stsTesti_img'  src='" . $this->baseUrl() . "/images/temp_img/author3.jpg'/>"; ?>
                                        <div class="stsTestimonial_content">
                                            <h3>Samar Khalil</h3>                      
                                            <span>Ex. Student</span>
                                            <p>Software Department</p>
                                        </div>
                                    </div>
                                </div>
                                <!-- End single student testimonial -->
                            </div>
                        </div>
                    </div>
                </div>
                <!-- End Our courses content -->
            </div>
        </section>
        <!--=========== END STUDENTS TESTIMONIAL SECTION ================-->    

        <!--=========== BEGIN FOOTER SECTION ================-->
        <footer id="footer">
            <!-- Start footer top area -->
            <div class="footer_top">
                <div class="container">
                    <div class="row">
                        <div class="col-ld-3  col-md-3 col-sm-3">
                            <div class="single_footer_widget">
                                <h3>About Us</h3>
                                <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.</p>
                            </div>
                        </div>
                        <div class="col-ld-3  col-md-3 col-sm-3">
                            <div class="single_footer_widget">
                                <h3>Community</h3>
                                <ul class="footer_widget_nav">
                                    <li><a href="#">Our Tutors</a></li>
                                    <li><a href="#">Our Students</a></li>
                                    <li><a href="#">Our Team</a></li>
                                    <li><a href="#">Forum</a></li>
                                    <li><a href="#">News &amp; Media</a></li>
                                </ul>
                            </div>
                        </div>
                        <div class="col-ld-3  col-md-3 col-sm-3">
                            <div class="single_footer_widget">
                                <h3>Others</h3>
                                <ul class="footer_widget_nav">
                                    <li><a href="#">Link 1</a></li>
                                    <li><a href="#">Link 2</a></li>
                                    <li><a href="#">Link 3</a></li>
                                    <li><a href="#">Link 4</a></li>
                                    <li><a href="#">Link 5</a></li>
                                </ul>
                            </div>
                        </div>
                        <div class="col-ld-3  col-md-3 col-sm-3">
                            <div class="single_footer_widget">
                                <h3>Social Links</h3>
                                <ul class="footer_social">
                                    <li><a data-toggle="tooltip" data-placement="top" title="Facebook" class="soc_tooltip" href="#"><i class="fa fa-facebook"></i></a></li>
                                    <li><a data-toggle="tooltip" data-placement="top" title="Twitter" class="soc_tooltip"  href="#"><i class="fa fa-twitter"></i></a></li>
                                    <li><a data-toggle="tooltip" data-placement="top" title="Google+" class="soc_tooltip"  href="#"><i class="fa fa-google-plus"></i></a></li>
                                    <li><a data-toggle="tooltip" data-placement="top" title="Linkedin" class="soc_tooltip"  href="#"><i class="fa fa-linkedin"></i></a></li>
                                    <li><a data-toggle="tooltip" data-placement="top" title="Youtube" class="soc_tooltip"  href="#"><i class="fa fa-youtube"></i></a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- End footer top area -->

            <!-- Start footer bottom area -->
            <div class="footer_bottom">
                <div class="container">
                    <div class="row">
                        <div class="col-lg-6 col-md-6 col-sm-6">
                            <div class="footer_bootomLeft">
                                <p> Copyright &copy; All Rights Reserved</p>
                            </div>
                        </div>
                        <div class="col-lg-6 col-md-6 col-sm-6">
                            <div class="footer_bootomRight">
                                <p>Designed by <a href="#" rel="nofollow">Wpfreeware.com</a></p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- End footer bottom area -->
        </footer>
        <!--=========== END FOOTER SECTION ================--> 

    </body>
</html>
