<table border="2">
    <tr>
        <th>Comment id</th>
        <th>Content</th>
        <th>User id</th>
        <th>EDIT</th>
        <th>DELETE</th>
    </tr>
    <?php

foreach ($this->comments as $comment) {
    ?>
    <tr>
        <td><?php $comment['id']?></td>
        <td><?php $comment['content']?></td>
        <td><?php $comment['user_id']?></td>
        <td><a href=".<?php $this->baseUrl();?>./public/comments/edit">EDIT</a></td>
        <td><a href=".<?php $this->baseUrl();?>./public/comments/delete">DELETE</a></td>
    </tr>
    
}
</table>






?>