<table border="2">
    <tr>
        <th style="padding:1em;">Comment id</th>
        <th style="padding:1em;">Content</th>
        <th style="padding:1em;">User id</th>
        <th style="padding:1em;">EDIT</th>
        <th style="padding:1em;">DELETE</th>
    </tr>
    <?php

foreach ($this->comments as $comment) {
    ?>
    <tr>
        <td><?php echo $comment['id'];?></td>
        <td><?php echo $comment['content'];?></td>
        <td><?php echo $comment['user_id'];?></td>
        <td><a href="<?php echo $this->baseUrl().'/comments/edit/id/'.$comment['id'];?>">EDIT</a></td>
        <td><a href="<?php echo $this->baseUrl().'/comments/delete/id/'.$comment['id'];?>">DELETE</a></td>
    </tr>
 <?php   
}

?>
</table>

