<?php // var_dump($this->comments);?>
<table class="table">
    <tr>
        <th >Comment id</th>
        <th >Content</th>
        <th >User id</th>
        <th >EDIT</th>
        <th >DELETE</th>
        
    </tr>
    <?php
if ($this->user["is_Admin"]==1){
foreach ($this->comments as $comment) {
    ?>
    <tr>
        <td><?php echo $comment['id'];?></td>
        <td><?php echo $comment['content'];?></td>
        <td><?php echo $comment['user_id'];?></td>
        <td><a href="<?php echo $this->baseUrl().'/comments/edit/id/'.$comment['id'];?>">EDIT</a></td>
        <td><a href="<?php echo $this->baseUrl().'/comments/delete/id/'.$comment['id'];?>">DELETE</a></td>
        
    </tr>
 <?php   
}
}  else {
    foreach ($this->comments as $comment) {
    ?>
    <tr>
        <td><?php echo $comment['id'];?></td>
        <td><?php echo $comment['content'];?></td>
        <td><?php echo $comment['user_id'];?></td>
        <?php if ($this->user["id"]==$comment['user_id'] ){ ?> 
        <td><a href="<?php echo $this->baseUrl().'/comments/edit/id/'.$comment['id'];?>">EDIT</a></td>
        <td><a href="<?php echo $this->baseUrl().'/comments/delete/id/'.$comment['id'];?>">DELETE</a></td>
        <?php }?>
    </tr>
 <?php   
}
}

?>
    
</table>
<?php // var_dump(Zend_Auth::getInstance()->getIdentity()->id);?>
<?php // echo Zend_Session::getId();?>

<a href="<?php echo $this->baseUrl().'/comments/add/id/'.$this->material_id;?>">add</a>

