<div class="row">
                <div class="col-lg-12 col-md-12"> 
                  <div class="title_area">
                    <h2 class="title_two">materials of <?php echo $this->course[0]['title'];?></h2>
                    <span></span> 
                  </div>
                </div>
              </div>

<?php
	foreach ($this->depmaterials as $m) {
		# code...
		if($m['is_shown']==1)
		{
		?>
		<div class="col-lg-3 col-md-3 col-sm-3">
                  <div class="single_whyus_top wow fadeInUp">
                    <div class="whyus_icon">
                    <a href="<?php echo $this->baseUrl();?>/userfront/contents/id/<?php echo $m['id'];?>">
                      <span style="font-size:30px;">
                      	 <?php echo $m['title'];?>
                      </span>
                      </a>
                    </div>
                    </div>
                  </div>
		<?php
	}
	}
?>