<div class="row">
                <div class="col-lg-12 col-md-12"> 
                  <div class="title_area">
                    <h2 class="title_two">single material</h2>
                    <span></span> 
                  </div>
                </div>
              </div>

<div>
	<p><a href="<?php echo $this->baseUrl();?>/materialcontent/display/content/<?php echo $this->single[0]['content_path'];?>"><?php echo $this->single[0]['content_path']; ?> </a></p>
</div>

<table class="table">
    <tr>
        <th >Comment id</th>
        <th >Content</th>
        <th >User id</th>
        <th >EDIT</th>
        <th >DELETE</th>
        
    </tr>
<?php
 foreach ($this->comments as $comment) {
    ?>
    <tr>
        <td><?php echo $comment['id'];?></td>
        <td><?php echo $comment['content'];?></td>
        <td><?php echo $comment['user_id'];?></td>
        <?php if ($this->user["id"]==$comment['user_id'] ){ ?> 
        <td><a href="<?php echo $this->baseUrl().'/comments/edit/id/'.$comment['id'];?>">EDIT</a></td>
        <td><a href="<?php echo $this->baseUrl().'/comments/delete/id/'.$comment['id'];?>">DELETE</a></td>
        <?php }?>
    </tr>
 <?php   
}
?>

</table>
<a href="<?php echo $this->baseUrl().'/comments/add/id/'.$this->material_id;?>">add</a>